### ISSUE TITLE
This control scheme is not the same as the Reverb G2 (also WMR).

### ISSUE THREAD

**Issue by Shilar** [MicrosoftDocs/altspace-vr#10]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2095ad7-420a-8852-5f36-0c4fa60150d7
* Version Independent ID: a73a63b2-1276-b9b2-a459-c1c86b3ccc97
* Content: [Windows Mixed Reality controls - AltspaceVR](https://docs.microsoft.com/en-us/windows/mixed-reality/altspace-vr/getting-started/wmr-controls)
* Content Source: [altspace-vr/getting-started/wmr-controls.md](https://github.com/MicrosoftDocs/altspace-vr/blob/main/altspace-vr/getting-started/wmr-controls.md)
* Product: **mixed-reality**
* GitHub Login: @vryunji
* Microsoft Alias: **v-hferrone**

**Comment by qianw211** [comment]
This should now be fixed.
