### ISSUE TITLE
Below age 

### ISSUE THREAD

**Issue by tay2012** [MicrosoftDocs/altspace-vr#11]
I let my dads worker little girl play on my altspace account she is 9 and I’m 28 I’m not below age she was just checking it out I’m so I broke the policy I won’t do it again 
![03F3FE27-46C3-4149-B713-DFE52E7FCF93](https://user-images.githubusercontent.com/83525070/116804953-88409300-aae8-11eb-878a-3be7746354bd.jpeg)

**Comment by vryunji** [comment]
Hello Tay,

We suggest that you send in a support ticket disputing the suspension to https://help.altvr.com/ in order to resolve this issue.

Best regards,
The Events Team

**Comment by tay2012** [comment]
What do you mean?


Sent from Yahoo Mail for iPhone


On Friday, June 25, 2021, 5:49 PM, vryunji ***@***.***> wrote:




Hello Tay,

We suggest that you send in a support ticket disputing the suspension to https://help.altvr.com/ in order to resolve this issue.

Best regards,
The Events Team

**Comment by vryunji** [comment]
Hello Tay,

On May 2nd, you mentioned that your father's coworker's child accessed your AltspaceVR account and that your AltspaceVR account was suspended. For requests like these in the future, you can get them resolved by sending in a support ticket to https://help.altvr.com/ . The requests we have through GitHub are for editing our documentation.

Best regards,
The Events Team

**Comment by tay2012** [comment]
Yeah I already have my altspace account back sorry 


Sent from Yahoo Mail for iPhone


On Friday, June 25, 2021, 5:58 PM, vryunji ***@***.***> wrote:




Hello Tay,

On May 2nd, you mentioned that your father's coworker's child accessed your AltspaceVR account and that your AltspaceVR account was suspended. For requests like these in the future, you can get them resolved by sending in a support ticket to https://help.altvr.com/ . The requests we have through GitHub are for editing our documentation.

Best regards,
The Events Team
