### ISSUE TITLE
Not sure how to access the console to delete the old uploader

### ISSUE THREAD

**Issue by CathyMoya** [MicrosoftDocs/altspace-vr#14]
Hi, I'm still bumbling my way around Unity. I installed the old uploader a few months ago, but with the upgrade I can't figure out how to do this:

"With Unity closed, delete the following files/folders, and it's corresponding .meta files"
Am I just deleting this in Explorer? I had to go searching and it looks like this is in the same folder as the world I created. It would help to provide more info for people not experience with Unity. 

Also, I think "it's corresponding .meta files" should be "its corresponding .meta files", possessive, not "it is", yes? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 529e033a-84ff-cf6a-846d-35544d06edff
* Version Independent ID: 60d62225-944b-deaf-2898-0b759f2e7922
* Content: [Updating Content to the Latest Unity Version - AltspaceVR](https://docs.microsoft.com/en-us/windows/mixed-reality/altspace-vr/world-building/upgrading-content-to-the-latest-unity)
* Content Source: [altspace-vr/world-building/upgrading-content-to-the-latest-unity.md](https://github.com/MicrosoftDocs/altspace-vr/blob/main/altspace-vr/world-building/upgrading-content-to-the-latest-unity.md)
* Product: **mixed-reality**
* GitHub Login: @vryunji
* Microsoft Alias: **v-hferrone**

**Comment by vryunji** [comment]
Hello Cathy,

Thanks for reaching out and apologies in our delay in reporting.

For this, we suggest that you delete the files with Unity open. That way you can easily find the project folder. You usually don't have to delete the Library folder. Basically, you will need to find these files and folders in your unity project's folder.

You can also ask for help in our Discord channel if you require additional assistance beyond this within our "#unity-uploader" channel.
