### ISSUE TITLE
please define all roles

### ISSUE THREAD

**Issue by RickGomez99** [MicrosoftDocs/altspace-vr#16]
Still missing the following roles:

Presenter, Doodler

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0ae60f6-0618-63fc-dfcf-dbba252fa59b
* Version Independent ID: 317380bb-fe04-f538-abde-ebf89738a1d0
* Content: [Roles in events, worlds, groups, and in AltspaceVR - AltspaceVR](https://docs.microsoft.com/en-us/windows/mixed-reality/altspace-vr/getting-started/roles)
* Content Source: [altspace-vr/getting-started/roles.md](https://github.com/MicrosoftDocs/altspace-vr/blob/main/altspace-vr/getting-started/roles.md)
* Product: **mixed-reality**
* GitHub Login: @vryunji
* Microsoft Alias: **v-hferrone**

**Comment by vryunji** [comment]
The presenter and doodler roles were recently removed, so no documentation is needed here. :)
