### ISSUE TITLE
Is there a way to display the camera view to a screen within the world?

### ISSUE THREAD

**Issue by keerkeer27** [MicrosoftDocs/altspace-vr#19]
I know there is because there is a kit for that on the altspace web based world building area.   is there anyway to use that kit in unity or anyway to use a camera to project its view onto a screen inside the world (so the users could see themselves in realtime).   I have been scouring the asset store with no luck.  if there is a way and instructions in the unity manual it would be great to get a link from this page. 

[Enter feedback here]

I used this feature so people could pick up items while building in altspace's world building area.  it would be great to link to a page (in the unity manual) that explains how to do it in unity.  

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d51d82b-f64a-714f-6f55-81b7e3c65f79
* Version Independent ID: e984043c-57b6-7a72-e63d-1acaf196987e
* Content: [Using the Interactables Spawner - AltspaceVR](https://docs.microsoft.com/en-us/windows/mixed-reality/altspace-vr/tutorials/interactable-spawner)
* Content Source: [altspace-vr/tutorials/interactable-spawner.md](https://github.com/MicrosoftDocs/altspace-vr/blob/main/altspace-vr/tutorials/interactable-spawner.md)
* Product: **mixed-reality**
* GitHub Login: @vryunji
* Microsoft Alias: **v-hferrone**

**Comment by qianw211** [comment]
Hi @keerkeer27,

We would suggest you search through the Unity documentation to help find your answer. Another suggestion is to take a look through developer.altvr.com or ask on our Discord in the world-building section: https://discord.gg/AjPegS9.

Best regards,
Qian
