### ISSUE TITLE
no setup instructions for Rift/Vive?

### ISSUE THREAD

**Issue by CathyMoya** [MicrosoftDocs/altspace-vr#22]
[Enter feedback here]
The Rift and HTC Vive are listed as supported but there are no links to instructions and no pages with instructions in the TOC. That's confusing....:-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23064123-957e-1733-fb6a-45359f478eba
* Version Independent ID: 8ffba7e4-2717-8ce8-ccc7-623e835a3916
* Content: [Minimum system requirements - AltspaceVR](https://docs.microsoft.com/en-us/windows/mixed-reality/altspace-vr/getting-started/system-requirements)
* Content Source: [altspace-vr/getting-started/system-requirements.md](https://github.com/MicrosoftDocs/altspace-vr/blob/main/altspace-vr/getting-started/system-requirements.md)
* Product: **mixed-reality**
* GitHub Login: @vryunji
* Microsoft Alias: **v-hferrone**

**Comment by qianw211** [comment]
Hi @CathyMoya ,

Thank you for your feedback. We will inform the documentation team about this.

Sincerely,
Qian
