### ISSUE TITLE
Mods to original world are being auto updated, contrary to the doc

### ISSUE THREAD

**Issue by CathyMoya** [MicrosoftDocs/altspace-vr#23]
[Enter feedback here]
The topic says: "Modifications made to the original world won't be in the event world unless the event space is updated:"
That's not the experience I'm having right now. Not sure if that's by design now or not, but I get consistent repro - I change something in my world, and it shows up in every event based on that world, both events that are current in process and events that are scheduled for the future. I'm going to file this under support as well, since I'm not sure if the behavior is by design. Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ca1a987-883c-d220-2057-ccdac022a8e1
* Version Independent ID: 18bc14ba-096d-91d2-d1bc-20e5a761bbdb
* Content: [Creating an event - AltspaceVR](https://docs.microsoft.com/en-us/windows/mixed-reality/altspace-vr/tutorials/creating-an-event)
* Content Source: [altspace-vr/tutorials/creating-an-event.md](https://github.com/MicrosoftDocs/altspace-vr/blob/main/altspace-vr/tutorials/creating-an-event.md)
* Product: **mixed-reality**
* GitHub Login: @vryunji
* Microsoft Alias: **v-hferrone**

**Comment by vryunji** [comment]
Hello Cathy,
When you have an upcoming event, it's good practice to always add things to a world, reimport your world to the event, and reset your space. Though you may see the changes immediately in your event just fine on your end, you open yourself up to a buggy experience. Reimporting and resetting the space reminds the system that a change has actually occurred.

Additionally, if you have someone who is in the event space who hasn't left, they will not see your changes happening in real time. Until the space gets reset, they will only see how it once was.

Hope this helps to clear some things up!
