### ISSUE TITLE
Is XBOX X wireless controller supported?

### ISSUE THREAD

**Issue by peterquirk** [MicrosoftDocs/altspace-vr#26]
Is there support for the Xbox X wireless controller? On Windows 11 I can move (left stick) but can't turn (right trigger + right stick on Xbox 360 controller.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0d96a80-8054-dcce-c317-716fcc6245e0
* Version Independent ID: 59b2cba0-9b33-e188-7959-676b87a2fb61
* Content: [Using a Gamepad in AltspaceVR - AltspaceVR](https://docs.microsoft.com/en-us/windows/mixed-reality/altspace-vr/getting-started/gamepad-controls)
* Content Source: [altspace-vr/getting-started/gamepad-controls.md](https://github.com/MicrosoftDocs/altspace-vr/blob/main/altspace-vr/getting-started/gamepad-controls.md)
* Product: **mixed-reality**
* GitHub Login: @qianw211
* Microsoft Alias: **v-qianwen**

**Comment by qianw211** [comment]
Hi @peterquirk 

We are currently updating this article for Xbox Controllers. Thank you for your patience.

Sincerely,
Qian

**Comment by peterquirk** [comment]
Thanks!
________________________________
