### ISSUE TITLE
Business VR platform meaning is vague

### ISSUE THREAD

**Issue by stephenc87** [MicrosoftDocs/altspace-vr#27]
"AltspaceVR will turn into a business VR platform" isn't very descriptive
Currently one might visit AltspaceVR and build their business model accordingly, as it also provides a social atmosphere that allows other users to engage with providers with minimal effort

What does a business VR platform offer? Will businesses need to change to keep up with this transformation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7f2cd55-ee7f-ffb2-d991-1835f02acf20
* Version Independent ID: 6d482315-c30e-0ce4-29c0-0195c2edfbd2
* Content: [AltspaceVR overview - AltspaceVR](https://docs.microsoft.com/en-us/windows/mixed-reality/altspace-vr/overview)
* Content Source: [altspace-vr/overview.md](https://github.com/MicrosoftDocs/altspace-vr/blob/main/altspace-vr/overview.md)
* Product: **mixed-reality**
* GitHub Login: @qianw211
* Microsoft Alias: **v-qianwen**

**Comment by qianw211** [comment]
Hi @stephenc87,

- Mesh will be the business platform once it is released.
- Complete the Microsoft Mesh Register Interest form to stay up to date with Mesh news and announcements: https://aka.ms/meshsignup

Best regards,
Qian
