### ISSUE TITLE
Mesh enabled altspace vr request

### ISSUE THREAD

**Issue by TiffAspy** [MicrosoftDocs/altspace-vr#28]
Hello,

I would like to download the mesh enabled altspace vr app. The link is currently down. Would you be able to provide me the download link?

Tiffany Aspy
Www.linktr.ee/revcreation

**Comment by qianw211** [comment]
Hi @TiffAspy,

Please check out our latest docs page on this:

- https://docs.microsoft.com/en-us/mesh/get-started webpage has been updated
-Microsoft Mesh is currently available in limited free preview. During the preview, you can try the Mesh app on your HoloLens.
-Complete the Microsoft Mesh Register Interest form to stay up to date with Mesh news and announcements: https://aka.ms/meshsignup

We will continue to make updates to reflect the latest releases of Mesh and AltspaceVR.  Please stay tuned!

Best regards,
Qian

**Comment by TiffAspy** [comment]
Is the altspacevr mesh app available on the pc or oculus quest 2? I don’t
have a HoloLens

**Comment by qianw211** [comment]
Hi @TiffAspy,
Currently the mesh app preview is only available on HoloLens 2.  We don't have Mesh app available for PC or Oculus Quest as for yet.  We'll be making future announcements once they become available. Thanks!
