### ISSUE TITLE
AltSpaveVR doesn't appear in Apps & Features

### ISSUE THREAD

**Issue by kcovert** [MicrosoftDocs/altspace-vr#29]
I have both the Steam and Oculus PC versions installed, neither show up. I would like to launch AltSpaceVR programmatically from my UWP app but can't see anywhere where thats possible. Can't find a launch Protocol call for AltSpaceVR either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f47cfa4-f914-2998-4707-18ad6673a2e0
* Version Independent ID: 11a54ffa-0d78-6d0b-5b85-50dbdeb09003
* Content: [Frequently asked questions about the AltspaceVR app - AltspaceVR](https://docs.microsoft.com/en-us/windows/mixed-reality/altspace-vr/faqs/altspacevr-app-faq)
* Content Source: [altspace-vr/faqs/altspacevr-app-faq.md](https://github.com/MicrosoftDocs/altspace-vr/blob/main/altspace-vr/faqs/altspacevr-app-faq.md)
* Product: **mixed-reality**
* GitHub Login: @qianw211
* Microsoft Alias: **qianwen**

**Comment by qianw211** [comment]
Hi @kcovert, we're not exactly sure how to program that, but if you have AltspaceVR installed on your PC and you click a hyperlink from the AltspaceVR website: https://account.altvr.com/events/my (Note, you will need to sign in to the website with your Altspace account.)

or click ENTER NOW, which goes to this link and will 'typically' fire up the AltspaceVR app and send you into that event, the link structure is altspace://account.altvr.com/api/events/XXXXXXXXXXXXXXXXXXX (where Xs are your eventID)

Please let me know if this will work for you, or you need more dev support. Thanks!

**Comment by kcovert** [comment]
I'll try that, thanks Qian, and report back on how it works out.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kcovert** [comment]
Ok to keep this closed. Have only partially tested this approach but looks promising, see attached. Must modify my test event date before next test. Will let you know how it goes,

Kirk

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kcovert** [comment]
As promised the outcome. Works well and will be a feature shipped in the app. Still hope for a more direct way into Altspace or Mesh but this will do for now. My app should ship soon. One of its tenants is to be a transitional app in the move from 2D to mixed reality,

Kirk

**Comment by qianw211** [comment]
@kcovert, Great to hear! Thanks for your feedback!
