### ISSUE TITLE
Granting World Roles #1 is inaccurate.

### ISSUE THREAD

**Issue by younitee** [MicrosoftDocs/altspace-vr#3]
**In VR > Roles**
does not exist.
instead I see:
**In VR > Default Contextual Roles**
and it is an input text field NOT a textarea
therefore, it is not possible to assign particular roles to specific users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca671541-f63d-41f8-9fb6-2c5b096b8e78
* Version Independent ID: 075d34df-bac0-fdb4-081a-5fff400e654f
* Content: [Granting world roles](https://docs.microsoft.com/en-us/windows/mixed-reality/altspace-vr/world-building/granting-roles)
* Content Source: [altspace-vr/world-building/granting-roles.md](https://github.com/MicrosoftDocs/altspace-vr/blob/main/altspace-vr/world-building/granting-roles.md)
* Product: **mixed-reality**
* GitHub Login: @vryunji
* Microsoft Alias: **v-hferrone**

**Comment by hferrone** [comment]
This has been updated, thanks for the callout!
