### ISSUE TITLE
Seam in skybox bug

### ISSUE THREAD

**Issue by RobbeVlaeminck** [MicrosoftDocs/altspace-vr#33]
[Enter feedback here]

The seam in skybox bug is still here. On your page you mention you will fix it 'soon'but hasnt been updated in over a year.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ef80b53-e570-95f8-f779-8135ac82b757
* Version Independent ID: 503260de-77f1-dfe6-9b80-c91fefb23086
* Content: [Uploading custom Skyboxes - AltspaceVR](https://docs.microsoft.com/en-us/windows/mixed-reality/altspace-vr/world-building/uploading-custom-skyboxes)
* Content Source: [altspace-vr/world-building/uploading-custom-skyboxes.md](https://github.com/MicrosoftDocs/altspace-vr/blob/main/altspace-vr/world-building/uploading-custom-skyboxes.md)
* Product: **mixed-reality**
* GitHub Login: @vryunji
* Microsoft Alias: **v-hferrone**

**Comment by qianw211** [comment]
This issue was updated and not we no longer have a line or seam in the sky!
