### ISSUE TITLE
Create a World Hyperlink Broken 

### ISSUE THREAD

**Issue by UniVRsity** [MicrosoftDocs/altspace-vr#4]
[Enter feedback here]
The create a world button directs you to a 404 page which makes it difficult for new learners to understand that step. Please update it with the proper link. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1509f334-ece6-5789-61f6-cab62e73cb33
* Version Independent ID: c5a57a0c-112b-8589-3307-da07d47ba329
* Content: [Introducing the World Building Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/altspace-vr/world-building/world-building-toolkit-getting-started)
* Content Source: [altspace-vr/world-building/world-building-toolkit-getting-started.md](https://github.com/MicrosoftDocs/altspace-vr/blob/main/altspace-vr/world-building/world-building-toolkit-getting-started.md)
* Product: **mixed-reality**
* GitHub Login: @vryunji
* Microsoft Alias: **v-hferrone**

**Comment by anthonyneaceVR** [comment]
Proposed Fix: https://github.com/MicrosoftDocs/altspace-vr/pull/5
